# Generated by Django 2.0.2 on 2018-02-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180227_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.TextField(default='None', max_length=10),
        ),
    ]
